version: '3.4'
services:
  web:
    image: nodejs_app
    build:
     context: .
     dockerfile: ./Dockerfile
    ports:
     - 8082:8082
  redis-server:
    image: 'redis'
    ports:
     - 6379:6379
  
